chore(addTeam-From): Cleaning code of AddTeam, created local state to save and creat member data.
sebikap-gm2/First-Plug-Platform-Client pull request #105
Opened 2023-10-26 15:13 UTC by Francisco-Villanueva

- In the "AddTeam" component, remove all "useInputs."

- Create a local state called "memberData" to store all the information of the new member to be created.
![image](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/90634174/2a7d4051-3d10-46b9-9f98-06663747950b)

- Create an input handler ("handleInput") to set the corresponding data in the "memberData" state.
![image](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/90634174/5b38c547-2d34-462d-a6f8-10391f4bca56)

- Create a "FormInput" component in which you use the common "Input" and make use of "useInput." Add a "options" prop for when the input is of type "select," allowing you to use the common "DropdownInput."
![image](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/90634174/d61582f4-6681-4b61-99eb-d1264d68f452)

- Create a layout for the sections of the form, which you use as a container for the inputs.
![image](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/90634174/1c8366ad-2569-464c-aa08-fa3ba0993c0f)

Implementation of the layout:
![image](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/90634174/16f6a4f6-3bb2-41ab-baee-b9156365fcdd)

- Create a common "SectionTitle" for the titles of each section of the form.
![image](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/90634174/d89b4168-a64d-46b8-a339-e4e358c0eb97)

Implementation of the SectionTitle:
![image](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/90634174/436f726a-b8a7-4dcc-83a3-198e2dce940e)

2023-10-26 15:42 UTC, sebikap-gm2 requested changes

2023-10-26 15:42 UTC, sebikap-gm2 commented on src/app/home/addTeam/page.jsx
> +  const [memberData, setMemberData] = useState({
Mover el objeto afuera a un `const INITIAL_MEMBER_DATA = { ... }`

2023-10-26 15:42 UTC, sebikap-gm2 commented on src/app/home/addTeam/page.jsx
>        .then((res) => {
Ya no es necesario borrar los inputs? En caso que sí, usemos el `INITIAL_MEMBER_DATA`

2023-10-26 19:52 UTC, Francisco-Villanueva commented on src/app/home/addTeam/page.jsx
>        .then((res) => {
- Seba, para esta parte no era tan sencillo como settear el estado en `INITIAL_MEMBER_DATA`, sino que tuve que crear un estado "finish"de tipo booleano. 

Cuanto el estado finish es true, utilizo la funcion clearInput del hook useInput

2023-11-03 00:27 UTC, sebikap-gm2 approved these changes

2023-11-03 13:38 UTC, merged