chore(environments): configured environments
sebikap-gm2/First-Plug-Platform-Client pull request #109
Opened 2023-10-31 22:52 UTC by nahuelRo

2023-11-03 00:51 UTC, sebikap-gm2 requested changes

2023-11-03 00:51 UTC, sebikap-gm2 commented on src/services/auth.services.js
> +      `${process.env.NEXT_PUBLIC_API_URL}/api/auth/register`,
Just for code clarity, add a `const BASE_URL = process.env.NEXT_PUBLIC_API_URL` on top and use that one

2023-11-03 01:53 UTC, nahuelRo commented on src/services/auth.services.js
> +      `${process.env.NEXT_PUBLIC_API_URL}/api/auth/register`,
I already made the changes

2023-11-07 21:46 UTC, sebikap-gm2 approved these changes

2023-11-07 21:49 UTC, merged