chore: refactored Aside component
sebikap-gm2/First-Plug-Platform-Client pull request #110
Opened 2023-11-02 20:05 UTC by Francisco-Villanueva

Cree una store para manejar el aside, su tipo (que es lo que tiene que reenderizar) y si esta abierto o cerrado.

Cree una store para cada uno de los modelos creados sobre la root store:
![image](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/90634174/43a9cdaa-3825-4949-9a66-a7ec23f15d81)

Creea un AsideContent para hacer un reenderizado condicional sobre el contenido del Aside. Este se basa en el tipo  de aside guardado en su store:
![image](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/90634174/ae26b4a2-0bd2-4cd8-a8b5-f224e09fe3e8)

Reenderizo el componente Aside en el archivo layout.js de home:
![image](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/90634174/1a855834-4d7b-4759-8306-a62822576c51)

2023-11-03 00:43 UTC, sebikap-gm2 requested changes

2023-11-03 00:43 UTC, sebikap-gm2 commented on src/models/member.store.js
> +  .views((store) => ({
Views before actions

2023-11-03 00:43 UTC, sebikap-gm2 commented on src/models/member.store.js
> +      return store.members.filter(
`return store.members.find((member) => member._id === store.selectedMember);`
'find' expresses the intention better.

2023-11-03 00:43 UTC, sebikap-gm2 commented on src/models/member.store.js
> +    oneMember() {
In views, we should try to use the following approach:
instead of `oneMember`, `getSelectedMemeber`.
And instead of `getSelectedMember`, `get selectedMember`.

This allows us to access the view as a prop instead of a function. So in component you want to use it, instead of 
`store.member.getSelectedMember()`, you'll do `store.member.selectedMember`

2023-11-03 12:21 UTC, Francisco-Villanueva commented on src/models/member.store.js
> +    oneMember() {
Perfect!

2023-11-04 14:26 UTC, sebikap-gm2 approved these changes

2023-11-04 14:26 UTC, merged