fix(client-commons): fix commons and delete files that we dont use
sebikap-gm2/First-Plug-Platform-Client pull request #116
Opened 2023-11-13 13:31 UTC by BrianBts

2023-11-13 21:59 UTC, sebikap-gm2 requested changes

2023-11-13 21:59 UTC, sebikap-gm2 commented on src/models/products.store.ts
> +    productSelected: types.optional(types.string, ""),
selectedProductId

2023-11-13 21:59 UTC, sebikap-gm2 commented on src/common/State.tsx
> +    { state: "ORDER CONFIRMED", color: "-lightGreen" },
Typo

2023-11-13 21:59 UTC, sebikap-gm2 commented on src/common/State.tsx
>    const states = [
```
const Colors = {
   info: 'bg-lightBlue',
   warn: 'bg-lightYellow',
   success: 'bg-lightGreen',
   error: 'bg-lightRed',
} as const
type Color = keyof typeof Colors

type State = {
   state: OrderStatus | ShipmentStatus | ....
   color: Color
}

const state: State[]
```

2023-11-13 21:59 UTC, sebikap-gm2 commented on src/models/member.store.ts
> +  shipmentDetails: types.optional(types.string, ""),
This should live in the shipments section.

2023-11-13 21:59 UTC, sebikap-gm2 commented on src/common/Input.tsx
> +  const [showPassword, setShowPassword] = useState<boolean>(false);
Not needed. If default value is false, boolean is inferred

2023-11-13 21:59 UTC, sebikap-gm2 commented on src/common/Dropdown.tsx
> +  const [isOpen, setIsOpen] = useState<boolean>(false);
Same as other comment

2023-11-13 21:59 UTC, sebikap-gm2 commented on src/common/Button.tsx
> +const sizeVariantProps = ["big", "small"] as const
```
const Sizes = ["big", "small"] as const
type Size = typeof Sizes[number];
```

2023-11-14 12:43 UTC, sebikap-gm2 requested changes

2023-11-14 12:43 UTC, sebikap-gm2 commented on src/common/State.tsx
> +  "CONFIRMATION PENDING": "bg-lightPurple",
Colors should be:
```
const Colors = {
 info: 'bg-lightBlue',
 warn: 'bg-lightYellow',
 error: 'bg-lightRed',
 success: 'bg-lightGreen',
 disabled: ....,
 todo: ...
} as const
type Color = keyof typeof Colors
```

2023-11-14 12:43 UTC, sebikap-gm2 commented on src/common/State.tsx
> +const states: State[] = [
After solving previous Color comment, this should become:
```
const StateColors: Record<OrderStatus, Color> = {
  "CONFIRMATION PENDING": 'Todo',
  "PAYMENT PENDING": 'warn',
  "ORDER CANCELED": 'error',
  ....
} as const
```

2023-11-14 12:43 UTC, sebikap-gm2 commented on src/common/State.tsx
> +export default function State({ message, className }: StateProps) {
Message should be renamed to status, and of `type OrderStatus`.
Then, you don't need to do find in states. After solving previous comment:
`const color = StateColors[orderStatus]`

2023-11-14 12:43 UTC, sebikap-gm2 commented on src/models/member.store.ts
> +
Remove

2023-11-14 12:43 UTC, sebikap-gm2 commented on src/models/products.store.ts
> +    selectedProductId: types.optional(types.string, ""),
Let's default to undefined. For better validations. Change `types.optional` to` types.maybe`

2023-11-14 12:43 UTC, sebikap-gm2 commented on src/common/Button.tsx
> +type Variant = typeof ButtonVarianProps[number]
Variants, as well as Size, should be derived from the btnStyle object, which should be moved outside the component.
So it would go like this:

```
const ButtonStyles = {
  variant: {
    primary:
      "bg-blue text-white   hover:bg-gradient-to-r from-blue to-green ",
    secondary: "bg-white border border-blue hover:bg-hoverBlue  text-blue ",
    delete: "bg-white border border-red-500 hover:bg-hoverRed  text-red-500 ",
    text: "bg-white   text-blue  hover:bg-hoverBlue",
    alert: "text-error    hover:bg-hoverRed",
  },
  size: {
    big: "text-lg py-3 px-6",
    small: "text-sm  py-2 px-6",
  },
  disabled: {
    primary: "bg-light-grey    text-grey ",
    delete: "bg-light-grey    text-grey ",
    secondary: "bg-white   text-grey ",
    text: "bg-white    text-grey   ",
    alert: "bg-white   text-grey ",
  },
} as const

type Size = keyof typeof ButtonStyles['size']
type Variant = keyof typeof ButtonStyles['variant']
```

2023-11-14 12:43 UTC, sebikap-gm2 commented on src/common/Button.tsx
> +  variant?: Variant;
Variant and size should have a default value OR be mandatory

2023-11-15 12:47 UTC, BrianBts commented
**Status common testing after changes required:**
(now, the code is more easy to read and understand)

![Captura de pantalla 2023-11-15 a la(s) 09 06 44](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/129008931/a4ef9253-ab04-41c4-b9ff-ea929763ecf0)
![Captura de pantalla 2023-11-15 a la(s) 09 06 54](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/129008931/7b7fe432-8318-46ce-86d1-5c17a40519a6)

- I created a index.ts file for exports commons
- Common button modified, Size and Variant values was take of BtnStyle.
- Fix product type, "optional" to "maybe"

2023-11-16 20:23 UTC, sebikap-gm2 approved these changes

2023-11-16 20:23 UTC, merged