feat(client): client api conection
sebikap-gm2/First-Plug-Platform-Client pull request #129
Opened 2024-01-02 12:27 UTC by BrianBts

![WhatsApp Image 2024-01-01 at 14 46 30](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/129008931/0649adc0-dcb1-4b43-9e65-24a007e474c5)
![WhatsApp Image 2024-01-01 at 19 19 15 (1)](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/129008931/31cf2fbf-ba79-46b6-9346-19919752eb46)
![WhatsApp Image 2024-01-01 at 19 19 15](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/129008931/d92dfd80-c342-4c10-8128-4458ca42c67b)

2024-01-02 20:57 UTC, BrianBts commented on src/components/TableDetailsShipments.tsx
> +        {shipments.map((item:any) => (
type this

2024-01-04 12:53 UTC, sebikap-gm2 requested changes

2024-01-04 12:53 UTC, sebikap-gm2 commented on src/services/orders.services.ts
> +      `${BASE_URL}/api/orders${id}`,
Is this ok?? We should not be removing '/' in these changes

2024-01-04 12:53 UTC, sebikap-gm2 commented on src/components/GridTeam.tsx
> +export const GridTeam = function ({members}) {
GridTeamProps should exist and receive the type, or why not get them from the store?

2024-01-04 12:53 UTC, sebikap-gm2 commented on src/app/home/my-team/data/page.tsx
> +  // useEffect(() => {
No need to update?

2024-01-04 12:53 UTC, sebikap-gm2 commented on src/app/Providers.tsx
> +        date: new Date(shipment.date), // Check how received Date from API, if dont use this line, we've an error with Model
Date will be received in string ISO format. The model probably is expecting a Date object

2024-01-07 23:57 UTC, BrianBts commented on src/services/orders.services.ts
> +      `${BASE_URL}/api/orders${id}`,
Yes! you're correct. This was my mistake

2024-01-08 00:10 UTC, BrianBts commented on src/components/GridTeam.tsx
> +export const GridTeam = function ({members}) {
Yes, I decided that is better use the store for this component, so we can delete components props `"members"` to do this more clean

2024-01-08 00:16 UTC, BrianBts commented on src/app/home/my-team/data/page.tsx
> +  // useEffect(() => {
Yes, need update but i commented this part because use `TeamServices.getAllTeams()` that do a query to `/api/teams` and in the API we dont have any rute for this.

2024-01-08 00:29 UTC, BrianBts commented on src/app/Providers.tsx
> +        date: new Date(shipment.date), // Check how received Date from API, if dont use this line, we've an error with Model
Okok, I will modify this to receive in Client ISO format

2024-01-08 21:54 UTC, sebikap-gm2 requested changes

2024-01-08 21:54 UTC, sebikap-gm2 commented on src/app/Providers.tsx
> +      const shipmentsData = shipmentsResponse.data.map((shipment:  Shipment) => ({ //Here we've only Shipment data to hydrate store
Why are we doing this?

2024-01-08 21:54 UTC, sebikap-gm2 commented on src/app/home/my-team/data/page.tsx
> +  // useEffect(() => {
Talked with @Tute22 on how to obtain from DB the aggregated teams array. Sent the query to General channel in slack. Backend must provide this endpoint

2024-01-08 21:54 UTC, sebikap-gm2 commented on src/components/GridTeam.tsx
> +      {members.map((member: TeamMember) => (
We should be inferring the type, if it is not working, something else is wrong

2024-01-08 21:54 UTC, sebikap-gm2 commented on src/components/TableDetailsShipments.tsx
> +        {shipments.map((item: Product) => (
This does not make much sense. Or shipments variable is wrongly named (unlikely), or the type is wrong. 
We must rename item to a more clear variable name (shipment) and let typescript infer the type. Again, if it is inferred wrong, the error is elsewhere

2024-01-08 21:54 UTC, sebikap-gm2 commented on src/components/TeamMemberCard.tsx
> +  shipmentDetails?: (typeof status)[number];
This type is old, replace

2024-01-08 21:54 UTC, sebikap-gm2 commented on src/components/TeamMemberCard.tsx
> +              {/* {member.products.length} check this, because member dont've product field in types*/}
Remove

2024-01-20 15:39 UTC, sebikap-gm2 approved these changes

2024-01-20 15:39 UTC, merged