fix(Client): Fix UI (working progress)
sebikap-gm2/First-Plug-Platform-Client pull request #132
Opened 2024-01-26 00:45 UTC by BrianBts

2024-02-06 21:42 UTC, sebikap-gm2 requested changes

2024-02-06 21:42 UTC, sebikap-gm2 commented on src/common/StatusColors.tsx
> +export const JobPositionColors: Record<string, string> = {
Just do a list of 20 colors and go one job position by one taking one color

2024-02-06 21:42 UTC, sebikap-gm2 commented on src/components/TableDetails.tsx
> +            <State status={mapStatusToOrderStatus(shipment.status)} className="p-1" />
`text-transform: uppercase;`

2024-02-06 21:42 UTC, sebikap-gm2 commented on src/components/Table.tsx
> +  const toggleRow = (productId: any) => {
```
any -> string
any -> Product["_id"]
```

2024-02-06 21:42 UTC, sebikap-gm2 commented on src/app/home/my-team/page.tsx
> +            href=""
Redirect to add team member

2024-02-06 21:42 UTC, sebikap-gm2 commented on src/common/Graphs.tsx
> +  const quantity = data.quantity || 20;
Do not default this value

2024-02-26 22:40 UTC, sebikap-gm2 requested changes

2024-02-26 22:40 UTC, sebikap-gm2 commented on src/common/Layout.tsx
> +      className={`h-auto min-h-full mx-auto    flex-grow   ${className}`}
Please check space in between class names or I will die

2024-02-26 22:40 UTC, sebikap-gm2 commented on src/common/Graphs.tsx
> +            Assigned | <b> {quantity + 20} </b>
Remove horrendous hardcode

2024-02-26 22:40 UTC, sebikap-gm2 commented on src/common/Graphs.tsx
>    const info = {
Check if we can type this

2024-02-26 22:40 UTC, sebikap-gm2 commented on src/common/EquipmentRow.tsx
> +        {selectedMember?.firstName} {selectedMember?.lastName}
Remove component

2024-02-26 22:40 UTC, sebikap-gm2 commented on src/app/home/orders/page.tsx
> +      {/* {
Review

2024-02-26 22:40 UTC, sebikap-gm2 commented on src/app/home/my-team/DataTeam.tsx
> +        </CustomLink>
Move to own component (Maybe MyTeamAppBar/MyTeamHeader)

2024-02-26 22:40 UTC, sebikap-gm2 commented on src/app/home/my-stock/EmptyStock.tsx
> +        <div className="flex gap-2 ">
Move Empty state component to own component and use everywhere

2024-02-26 22:40 UTC, sebikap-gm2 commented on src/app/home/layout.tsx
> +  }, [session, store.members]);
```
const {
   members: { setMembers }
} = useStore();
```

Add to existing line 16

2024-02-29 20:49 UTC, Francisco-Villanueva commented on src/common/StatusColors.tsx
> +export const JobPositionColors: Record<string, string> = {
Do you mean something like that?

`export const JobPositionColors = [
  "bg-pink-400",
  "bg-green",
  "bg-purple",
  "bg-yellow-200",
  "bg-red-200",
];`

2024-02-29 21:05 UTC, Francisco-Villanueva commented on src/common/Graphs.tsx
>    const info = {
Fixed on ['fix/graph-stock-view'](https://github.com/sebikap-gm2/First-Plug-Platform-Client/pull/135) PR

2024-03-03 20:37 UTC, sebikap-gm2 requested changes

2024-03-03 20:37 UTC, sebikap-gm2 commented on src/components/TeamMembers.tsx
> +    <section className="flex flex-col gap-4 absolute  bottom-0 left-0 overflow-auto  h-[80%] w-full ">
We should avoid absolute positioning, it should be used only in certain cases. What was the issue here? There probably is a better solution using flexbox

2024-03-03 20:37 UTC, sebikap-gm2 commented on src/components/TeamHomeCard.tsx
> +export const TeamHomeCard = observer(function ({}: TeamCardProps) {
Avoid. No props -> no props object

2024-03-03 20:37 UTC, sebikap-gm2 commented on src/components/Card.tsx
> +      className={` felx flex-col  rounded-xl p-4  border border-border  relative ${className}`}
felx?

2024-03-03 20:37 UTC, sebikap-gm2 commented on src/components/Card.tsx
> +              Title ? "" : "absolute"
Avoid absolute. What's the issue here?

2024-03-03 20:37 UTC, sebikap-gm2 commented on src/common/EmptyCard.tsx
> +function EmptyCardChildren({ children }: { children: childrenTypes }) {
This is a step forward, but no exactly what I had in mind. Let's review together @Francisco-Villanueva

2024-03-03 20:37 UTC, sebikap-gm2 commented on src/common/DropFilter.tsx
> +export function DropFilter({ children, contentText }: DropFilterProps) {
Let's review together this component type

2024-03-03 20:37 UTC, sebikap-gm2 commented on src/app/home/shipments/EmptyShipments.tsx
> +    <EmptyCardLayout>
Review all together with Empty Card things

2024-03-12 20:18 UTC, merged