Feat/teables tan stack
sebikap-gm2/First-Plug-Platform-Client pull request #137
Opened 2024-03-02 19:23 UTC by Francisco-Villanueva

2024-03-19 20:49 UTC, sebikap-gm2 requested changes

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/app/home/my-stock/DataStock.tsx
> +    cell: ({ row }) => {
```
interface ExpanderCellProps {
   row: TableRow<unknown>
}
const ExpanderCell = ({ row }) => (
   ...
)
```

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/app/home/my-team/page.tsx
> +  useEffect(() => {
Remove

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/app/home/orders/EquipmentTable.tsx
> +        USD {getValue<Product[]>().reduce((a, b) => parseInt(b.price) + a, 0)}
Find out if we can avoid passing types and let ts infer them

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/app/home/shipments/DataShipments.tsx
> +import { format } from "date-fns";
God please no

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/app/home/shipments/DataShipments.tsx
> +            onClick={() => handleSelect(row.original.orderId)}
@Francisco-Villanueva Add meeting to review this

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/app/home/my-stock/DataStock.tsx
> +        <Table<Product>
```
interface ProductTableProps {
    products: Product[]
    internalProducts: Product[]
}

export const ProductTable = ({ products, internalProducts }: ProductTableProps) => {
   return (
      <Table<Product>
         data={products}
         columns={prodcutColumns({ serial: false })}
         getRowCanExpand={() => true}
         subComponent={internalProducts ? 
            <Table<Product> data={internalProducts} columns={InternalProductsColumns} /> : null
         }
      />
   )
}
```

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/app/home/shipments/ShipmentDetailsRow.tsx
> +  return (
Move to ProductTable component

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/app/home/shipments/DataShipments.tsx
> +        <Table<ShipmentTable>
`<ProductTable products={selectedShipment.products} />`

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/common/DropFilter.tsx
> +"use client";
Remove

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/common/TeamCard.tsx
>    const colors_role = {
Remove

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/components/Navbar.tsx
```
const Titles = {
   'my-stock': 'My Stock',
   'my-team': 'My Team'
} as const


<h1>{Titles[pathname] ?? ''}</h1>
```

2024-03-19 20:49 UTC, sebikap-gm2 commented on src/models/products.store.ts
> +          processor: product.processor || undefined,
No need for `|| undefined`

2024-03-20 12:18 UTC, Francisco-Villanueva commented on src/app/home/orders/EquipmentTable.tsx
> +        USD {getValue<Product[]>().reduce((a, b) => parseInt(b.price) + a, 0)}
![image](https://github.com/sebikap-gm2/First-Plug-Platform-Client/assets/90634174/fc779ba8-62dd-4c7a-81a4-fb240e50f5d7)

2024-03-26 20:55 UTC, sebikap-gm2 requested changes

2024-03-26 20:55 UTC, sebikap-gm2 commented on src/components/Navbar.tsx
> +  const Titles = {
Outside component

2024-03-26 20:55 UTC, sebikap-gm2 commented on src/utils/date.ts
> +  return day2 + "/" + month2 + "/" + year;
`new Date().toLocaleDateString('en')`

2024-03-26 20:55 UTC, sebikap-gm2 commented on src/components/Tables/ProductsTable.tsx
> +        Name & LastName
Add backend endpoint getAll that queries assigned and unassigned products.
**@Francisco-Villanueva THIS IS A TODO FOR A NEXT PR EHHHHHH**

2024-04-04 21:04 UTC, merged